### ISSUE TITLE
Installing “tree-ignore@0.2.6” failed (windows 7 x64)

### ISSUE THREAD

**Issue by acopalipsis** [leny/atom-tree-ignore#10]
when installing the plugin from atom -  
![2015-10-31_16-23-41](https://cloud.githubusercontent.com/assets/9849922/10863917/cc17ef06-7fec-11e5-9529-a3cc549f2855.png)

> runas@2.0.0 install C:\Users\ivan\AppData\Local\Temp\apm-install-dir-115931-2436-14t6s1h\node_modules\tree-ignore\node_modules\pathwatcher\node_modules\runas
>     node-gyp rebuild 
>     C:\Users\ivan\AppData\Local\Temp\apm-install-dir-115931-2436-14t6s1h\node_modules\tree-ignore\node_modules\pathwatcher\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\ivan\AppData\Local\atom\app-1.1.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )  
>  ���ઠ �஥�⮢ � �⮬ ��襭�� �� ������. �⮡� �������� ��ࠫ������� ᡮ���, �������� ��ࠬ��� "/m".  
>  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please install v120 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\ivan\AppData\Local\Temp\apm-install-dir-115931-2436-14t6s1h\node_modules\tree-ignore\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
>  npm ERR! Windows_NT 6.1.7601  
>  npm ERR! argv "C:\Users\ivan\AppData\Local\atom\app-1.1.0\resources\app\apm\bin\node.exe" "C:\Users\ivan\AppData\Local\atom\app-1.1.0\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\ivan\.atom\.apm\.apmrc" "--userconfig" "C:\Users\ivan\.atom\.apmrc" "install" "C:\Users\ivan\AppData\Local\Temp\d-115931-2436-v2i7vp\package.tgz" "--target=0.30.7" "--arch=ia32" "--msvs_version=2013"  
>  npm ERR! node v0.10.40  
>  npm ERR! npm  v2.13.3  
>  npm ERR! code ELIFECYCLE  
>  npm ERR! runas@2.0.0 install: `node-gyp rebuild`  
>  npm ERR! Exit status 1  
>  npm ERR!  
>  npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.  
>  npm ERR! This is most likely a problem with the runas package,  
>  npm ERR! not with npm itself.  
>  npm ERR! Tell the author that this fails on your system:  
>  npm ERR!     node-gyp rebuild  
>  npm ERR! You can get their info via:  
>  npm ERR!     npm owner ls runas  
>  npm ERR! There is likely additional logging output above.    

manual installation - 
![2015-10-31_16-19-32](https://cloud.githubusercontent.com/assets/9849922/10863931/8cd97d22-7fed-11e5-90ce-726cb7a39f7a.png)

> Cannot find module 'event-kit'  
>  Hide Stack Trace  
>  Error: Cannot find module 'event-kit'  
>      at Module._resolveFilename (module.js:334:15)  
>      at Function.Module._resolveFilename (C:\Users\ivan\AppData\Local\atom\app-1.1.0\resources\app.asar\src\module-cache.js:383:52)  
>      at Function.Module._load (module.js:284:25)  
>      at Module.require (module.js:363:17)  
>      at require (module.js:382:17)  
>      at Object.<anonymous> (file:///C:/Users/ivan/.atom/packages/tree-view/lib/main.coffee:1:25)  
>      at Object.<anonymous> (file:///C:/Users/ivan/.atom/packages/tree-view/lib/main.coffee:1:1)  
>      at Module._compile (module.js:428:26)  
>      at Object.defineProperty.value [as .coffee](C:UsersivanAppDataLocalatomapp-1.1.0resourcesapp.asarsrccompile-cache.js:169:21)  
>      at Module.load (module.js:353:32)

**Comment by PhiLhoSoft** [comment]
See issue #2

**Comment by bagusflyer** [comment]
Doesn't work in mac osx either.

**Comment by leny** [comment]
Hi,

This package is completely outdated, needs a big rewrite.
I'll try to rewrite it today or tomorrow.

**Comment by leny** [comment]
Hi, I've just published `0.3.0` version.

Since the internal dependencies have changed, it could be a good idea to run the following commands in a shell after the update : `apm rebuild` and `apm rebuild-module-cache`.

Unfortunately, I don't have a Windows computer at home right now. If someone can test the new version on windows and tell me if its okay, it would be really great.

Sorry for the long, _long_ time on this issue.
