### ISSUE TITLE
Version 0.4.0 is broken (on Windows)

### ISSUE THREAD

**Issue by PhiLhoSoft** [leny/atom-tree-ignore#11]
Version 0.3.1 was working fine, but when I upgraded to 0.4.0, it stopped to work.
On startup of Atom, I get the following stack trace:

```
Uncaught (in promise) DOMException: Failed to execute 'observe' on 'MutationObserver': The provided node was null.
    at Error (native)
    at _fUpdate (C:/Users/plhoste/.atom/packages/tree-ignore/lib/tree-ignore.js:67:28)
    at Emitter.module.exports.Emitter.emit (C:\Users\plhoste\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at C:\Users\plhoste\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package-manager.js:482:32
```

**Comment by leny** [comment]
Aw, f*ck, sorry for that.
It's very hard to debug on windows... without having windows :D

I'll try to install a VM tonight.

Since that, can you open the devtools of atom, and find the html element for the mail `<ol>` of the tree-view, and paste here his markup?

When the error occurs, had you a tree-view panel opened?

**Comment by PhiLhoSoft** [comment]
Investigating.
Note: this might not be related to Windows, I just added it for context...

And, indeed, I see the error probably because Atom opens an instance without tree-view.
That's at least, a case to handle to avoid hanging on such error...

I first thought it was because you used document.querySelector instead of the jQuery request you do elsewhere.

BTW, thanks for the quick answer.

**Comment by leny** [comment]
I think its more related to the absence of tree-view.
I'll push a fix in a minute.

**Comment by PhiLhoSoft** [comment]
OK, I opened back a project, to get a tree-view on start up, and indeed it was displayed after restarting Atom. But I still get the stack trace. I guess then it is a timing issue, ie. it might not be present yet.

**Comment by leny** [comment]
I've just pushed version `0.4.1`.
Hope it fixes this problem.

I will not close the issue yet: your issue helps me finds a bug : when you open Atom without tree-view and show it after initialization, tree-ignore isn't fired and need to be triggered by hand.

Will try to fix that tonight.

**Comment by leny** [comment]
Version `0.4.2` fix the problem when tree-view is hide on Atom's launch.

Can you confirm that all is okay on windows?

Thanks.

**Comment by PhiLhoSoft** [comment]
I can confirm it works, although the .gitignore syntax isn't always respected. But these remarks belong to another issue.

**Comment by leny** [comment]
Ok, thanks.
