### ISSUE TITLE
Should use paths relative to the project

### ISSUE THREAD

**Issue by PhiLhoSoft** [leny/atom-tree-ignore#12]
This package uses the paths reported by Atom. But these are absolute to the root of the system, not relative to the project.

For example, my project is at `/user/PLS/projects/awesome`. If I open `awesome` in Atom and if I put `PLS` in the `.atomignore` file, the whole project disappears!

Maybe this package should get the project path and remove this prefix from the paths before giving them to the `ignore` library.

**Comment by leny** [comment]
Thanks for the report.
I'll try to fix this tonight, more probably tomorrow.

**Comment by leny** [comment]
Hi, 
I've pushed a fix as version `0.4.3`, works well on OS X.

Can you test it on Windows?
