### ISSUE TITLE
Wrong .atomignore if several projects are opened

### ISSUE THREAD

**Issue by PhiLhoSoft** [leny/atom-tree-ignore#14]
I try to fix the issues I opened... It is a good way to get familiar with the Atom API... :wink: 

I thought of an issue, and indeed the behavior is not as expected: I can open two (or more) projects in Atom, each has its own root in the tree-view.
You use the non-public `resolvePath` function on Project, which has a caveat: https://github.com/atom/atom/blob/v1.3.2/src/project.coffee#L215 "_TODO: what should we do here when there are multiple directories?_"
Yeah, exactly!
So, `resolvePath` only fetches the first `.atomignore` (on the first project) and the package applies it to all opened projects! So we loose the specificity of the file... (Of course, it works if only one project is opened.)

The weakness is in the Atom API: the `Project` object is misnamed (probably for historical reasons...), since it is an umbrella for all opened projects, as the `getPaths` and `getDirectories` implies... So the private `resolvePath` is flaky!

As said, I will try and fix that...

**Comment by leny** [comment]
Ok, thanks for the issue. I let you work on this.
