### ISSUE TITLE
Feature request: also hide files from searches

### ISSUE THREAD

**Issue by PhiLhoSoft** [leny/atom-tree-ignore#19]
I would appreciate if this package added, probably as an opt in setting, the capability to hide files from searches.

In Atom, you have two settings: with the _Exclude VCS Ignored Paths_ setting: the files "_will be ignored by some packages, such as the fuzzy finder and find and replace_". But if I do a global find of a string in an ignored file, the file is in the search results. With the _Ignored Names_ setting, "_Files and directories matching these patterns will be ignored by some packages, such as the fuzzy finder and tree view._".

As said, one interest of your package is to manage projects with mixed languages, where you want to deal with only one. Typical usage: front-end in JS, back-end in another language, like Java. Not only I want to hide the back-end (I manage it with Eclipse, more powerful for Java than Atom), but I want to speed up searches and avoid false positives in the back-end if I search only in the UI.

This might need to do some research, to find out how Atom excludes the files from the above settings from searches.

**Comment by leny** [comment]
I think you might be interested by the [atom-local-config](https://github.com/leny/atom-local-config) package, when I try to supply a solution for this problem.
