### ISSUE TITLE
Closing and reopening a folder in the tree disables the ignore

### ISSUE THREAD

**Issue by thibaultcha** [leny/atom-tree-ignore#3]
I am running `0.2.5` on Atom 0.177 and Mac OS X.

I have an `.atomignore` file with the only line:

```
.DS_Store
```

When I open a recent project, some folders are expanded, some are not. I don't see any `.DS_Store` file in the tree.

By simply closing and reopening a folder in the tree, all `.DS_Store` files will appear in this folder's tree. Doing it for each folder and eventually I see all the ignored files in the tree.

**Comment by leny** [comment]
Hi, thanks for the report.

I will try to investigate it during the week-end. If you have time on your own, feel free to submit a Pull Request :)

**Comment by jantimon** [comment]
Hi @leny did you make any progress here?

**Comment by leny** [comment]
Sorry, I don't have time to look at that for now... very busy with pro work.
Feel free to investigate and submit a Pull Request.

**Comment by jantimon** [comment]
Do you know any documentations on three view events?

**Comment by leny** [comment]
Hi, did the new version fixes the bug here?

**Comment by jamesstidard** [comment]
I'm having the same problem. I'm on 0.3.1 and am seeing the same thing

**Comment by leny** [comment]
I think I know from where comes the problem. When a folder (an `ol`) is closed, Atom removes all the files elements (`li`'s) inside, so, when you re-open a folder, the li insides are "fresh and new".
I will look at this maybe tonight, probably tomorrow.

**Comment by leny** [comment]
I've just pushed version `0.4.0`, which fix this issue.

**Comment by jamesstidard** [comment]
That was quick. Thanks for the neat little package
