### ISSUE TITLE
Failed to load the tree-ignore package

### ISSUE THREAD

**Issue by thibaultcha** [leny/atom-tree-ignore#5]
Simply by starting Atom, this is what I get (this is the default text from Atom's popup suggesting to create an issue):

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: [tree-ignore](https://github.com/leny/atom-tree-ignore) package, v0.2.5
### Stack Trace

Failed to load the tree-ignore package

```
At Module version mismatch. Expected 43, got 41.

Error: Module version mismatch. Expected 43, got 41.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/thibaultcha/Documents/Dropbox/Mackup/.atom/packages/tree-ignore/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/Users/thibaultcha/Documents/Dropbox/Mackup/.atom/packages/tree-ignore/node_modules/pathwatcher/lib/main.js:207:4)
    at Module._compile (module.js:452:26)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autosave",
      "metrics",
      "welcome",
      "wrap-guide",
      "tabs-closer",
      "tabs",
      "tree-view",
      "tree-view-open-files",
      "linter-jscs",
      "linter-jshint"
    ],
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "audioBeep": false,
    "destroyEmptyPanes": false
  },
  "tree-ignore": {}
}
```
### Installed Packages

``` coffee
# User
Stylus, v0.7.0
autocomplete-plus, v2.8.0
file-icons, v1.5.3
git-log, v0.3.0
highlight-line, v0.10.1
language-jade, v0.3.0
language-lua, v0.9.2
linter, v0.12.0
linter-js-standard, v0.1.4
linter-lua, v0.1.5
pain-split, v1.3.1
sublime-tabs, v0.5.2
tree-ignore, v0.2.5

# Dev
No dev packages
```

I would really like to keep using this package tho

**Comment by leny** [comment]
Hi,

Thanks for the report.

I try to take a look at this as soon as possible.

**Comment by leny** [comment]
Hi, I've just published `0.3.0` version.

Since the internal dependencies have changed, it could be a good idea to run the following commands in a shell after the update : `apm rebuild` and `apm rebuild-module-cache`.

Unfortunately, I don't have a Windows computer at home right now. If someone can test the new version on windows and tell me if its okay, it would be really great.

Sorry for the long, _long_ time on this issue.

**Comment by dmcissokho** [comment]
Hi I have the same issue on the last release

**Comment by leny** [comment]
Hi, thanks for the reporting. 

I'm not an active user of Atom anymore (switched to vim a few months ago), but, for now, I'm mostly too busy with professional work and deadlines to be able to fix this package before a few months.

If anyone of you want to become a collaborator and do the work, I will be happy to include this person(s) on the collaborators list of the package.

Thanks :)
