### ISSUE TITLE
tree-ignore toggle command not working

### ISSUE THREAD

**Issue by michaelaye** [leny/atom-tree-ignore#7]
The keybord short cut interestingly just toggles the .git folder out and in of view.
Also, the command palette does not have any tree-ignore toggle command available.

**Comment by leny** [comment]
Hi, 

I've just removed the keymap shortcut on  the command, so you can set the one you want and avoid conflict.

Since the new version `0.3.0`, is this issue still an issue?

**Comment by michaelaye** [comment]
Sorry, due to lack of feedback I just uninstalled this plugin.

**Comment by michaelaye** [comment]
Ah, and I remember now, that I did not need it anyway, as the built-in treeview can ignore VCS ignored files already.
