### ISSUE TITLE
can this hide other files?

### ISSUE THREAD

**Issue by lewislepton** [leny/atom-tree-ignore#9]
ive tried hiding other files in my tree. such as `.asset` and a few others. they are not editable, but do spawn when using something in my projects. but since they are no use to edit, id like to be able to hide them.

but [currently] this does not hide them

thanks

**Comment by leny** [comment]
Hi, I've just published `0.3.0` version.

Since the internal dependencies have changed, it could be a good idea to run the following commands in a shell after the update : `apm rebuild` and `apm rebuild-module-cache`.

Sorry for the long, _long_ time on this issue.
